tests: fix failing tests due to Babel's LazyProxy
When Babel is installed, these tests failed with this exception:
TypeError: 'in <string>' requires string as left operand, not LazyProxy

Forcing conversion to a string solves the problem.